from . import stock_quant
from . import res_users
from . import res_company
from . import res_partner
from . import hr_attendance
from . import ticket_helpdesk
from . import project_task
from . import hr_employee
from . import device